name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  LFT-Automation:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Set up Node with version 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Get dependencies
        run: npm ci

      - name: Execute linter
        run: npm run lint